apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: e2e-basic-1777037571812
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/quay_xjiang/test-image:github-35fc7c36dcc0fdaae361d4c962858787470df29f
        name: container-image  
